config/routes.rb
Rails.application.routes.draw do
  get 'bookmarks/new'
  get 'bookmarks/create'
  get 'lists/index'
  get 'lists/show'
  get 'lists/new'
  get 'movies/seen' => 'movies#seen' # or match for older Rails versions
  get 'pages/home'

  # root to: 'lists#index'
  resources :movies do
    resources :bookmarks, only: [ :new, :create ]
  end
  resources :lists do
    resources :bookmarks, only: [ :new, :create, :destroy]
  end

  devise_for :users
  root to: 'pages#home'

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :movies, only: [ :index, :show, :create, :destroy ]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates_uniqueness_of :movie, scope: [:list]
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks
  has_many :movies, through: :bookmarks, dependent: :destroy
  validates :name, presence: true, uniqueness: { scope: :user }
  belongs_to :user
  has_one_attached :photo
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  validates :title, presence: true, uniqueness: { scope: :user_id }

  include PgSearch::Model
  pg_search_scope :global_search,
                  against: [ :title, :overview, :actor, :director ],
                  using: {
                    tsearch: { prefix: true }
    }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :lists
  validates :nickname, presence: true, uniqueness: true, length: { maximum: 10 }
end

app/controllers/api/v1/movies_controller.rb
class Api::V1::MoviesController < ApplicationController
  def index
    # sql_query = " \
    #   movies.title ILIKE :query \
    #   OR movies.overview ILIKE :query \
    #   OR movies.actor ILIKE :query \
    #   OR movies.director ILIKE :query \
    # "
    # @movies = @user_movies.where(sql_query, query: "%#{params[:query]}%")
    @user_movies = Movie.where(user_id: current_user.id)
    @movies = @user_movies.order("title ASC")
    render json: @movies
  end

  def show
    @movie = Movie.find(params[:id])
    render json: @movie
  end

  def create
    @movie = Post.create(post_params)
    render json: @movie
  end

  private

  def post_params
    params.require(:movie).permit(:id, :title, :poster_url, :overview, :rating, :year, :youtube_url, :seen, :seen_date)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:nickname])
  end

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    @bookmark.user_id = current_user.id
    if @bookmark.save
      redirect_to list_path(@list)
    else render :new
    end
  end

  def destroy
    @list = List.find(params[:id])
    @bookmark = Bookmark.find_by_movie_id(params[:list_id])
    @bookmark.destroy
    redirect_to list_path(@list)
  end

    private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :list_id, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
    @user_lists = List.where(user_id: current_user.id)
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.user_id = current_user.id
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    @list = List.find(params[:id])
    @list.update(list_params)

    redirect_to list_path(@list)
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path
  end

  private

  def list_params
    params.require(:list).permit(:id, :name, :poster_url, :photo)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @user_movies = Movie.where(user_id: current_user.id)
    if params[:query].present?
      sql_query = " \
        movies.title ILIKE :query \
        OR movies.overview ILIKE :query \
        OR movies.actor ILIKE :query \
        OR movies.director ILIKE :query \
      "
      @movies = @user_movies.where(sql_query, query: "%#{params[:query]}%")
    else
      @movies = @user_movies.order("title ASC")
    end
  end

  def show
    @movie = Movie.find(params[:id])
  end

  def seen
    @user_movies = Movie.where(user_id: current_user.id)
    @seen_movies = @user_movies.where(seen: true).order("title ASC")
    @unseen_movies = @user_movies.where(seen: false).order("title ASC")
  end

  def new
    @movie = Movie.new
  end

  def create
    create_a_movie(params[:movie][:title])
    @movie = Movie.new
    if params[:movie][:youtube_url].present?
      create_youtube_link(params[:movie][:youtube_url])
    end
    @movie.title = @movie_api["Title"]
    @movie.overview = @movie_api["Plot"]
    @movie.poster_url = @movie_api["Poster"]
    if @movie_api["Ratings"][0]["Value"].present?
      @movie.rating = @movie_api["Ratings"][0]["Value"]
    end
    @movie.year = @movie_api["Year"]
    @movie.actor = @movie_api["Actors"]
    @movie.director = @movie_api["Director"]
    @movie.genre = @movie_api["Genre"]
    @movie.user_id = current_user.id
    if @movie.save
      redirect_to movies_path
    else render :new
    end
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def update
    @movie = Movie.find(params[:id])
    if @movie.youtube_url.present?
      youtube_url = @movie.youtube_url
    end
    @movie.update(movie_params)
    if params[:movie][:youtube_url].present?
      url_pattern = /^(https:\/\/www.youtube.com\/embed\/)(.*)$/
      if params[:movie][:youtube_url].match?(url_pattern)
        @movie.youtube_url = params[:movie][:youtube_url]
      else
        @movie.youtube_url = create_youtube_link(params[:movie][:youtube_url])
      end
    end
    @movie.save

    redirect_to movie_path(@movie)
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy

    # no need for app/views/movies/destroy.html.erb
    redirect_to movies_path
  end

  private

  def create_youtube_link(url)
    url_pattern = /^(https:\/\/youtu.be\/)(.*)$/
    if url.match?(url_pattern)
      pattern = /^(?<youtube>https:\/\/\youtu.be\/)(?<link>.*)$/
      match_data = url.match(pattern)
      @movie.youtube_url = "https://www.youtube.com/embed/#{match_data[:link]}"
    end
  end

  def movie_params
    params.require(:movie).permit(:id, :title, :poster_url, :overview, :rating, :year, :youtube_url, :seen, :seen_date)
  end

  def create_a_movie(title)
    require 'json'
    require 'open-uri'
    url = "http://www.omdbapi.com/?apikey=869d756e&t=#{title}"
    movie_api_serialized = URI.open(url).read
    @movie_api = JSON.parse(movie_api_serialized)
    # puts "#{user["Title"]} - #{user["Year"]} - #{user["Genre"]} - #{user["Director"]} - #{user["Actors"]} - #{user["Plot"]} - #{user["Poster"]} - #{user["Value"]}"
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # skip_before_action :authenticate_user!, only: [ :home ]

  def home
    @movies = Movie.all
    @lists = List.all
  end
end

app/helpers/api/v1/movies_helper.rb
module Api::V1::MoviesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def comment
  end
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bookmarks/index.html.erb
<% @bookmarks.each do |bookmark| %>
  <h1><%= bookmark.comment %></h1>
<% end %>

app/views/bookmarks/new.html.erb
<div class="new-bookmark-container">
<h3>Add a movie to your <%= @list.name %> list</h3>
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.association :movie, prompt: 'Select a movie', input_html: { class: 'select2' }, multiple: true %>
  <%= f.input :comment, placeholder: 'Enter a comment about the movie' %>
  <hr>
  <%= f.submit "Add this movie", class: 'btn btn-primary' %>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My Watch List</title>
    <%= favicon_link_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

<%= render 'shared/navbar' %>


  <div id="up-arrow-container" class="hidden-arrow">
    <i class="fas fa-arrow-up"></i>
  </div>

    <%= yield %>

  <p id="notice"><%= notice %></p>
  <p id="alert"><%= alert %></p>

    <%= javascript_pack_tag 'movies' %>
  </body>
</html>

app/views/lists/edit.html.erb
<h1>Edit list</h1>

<%= simple_form_for [@list] do |f| %>
  <%= f.input :name %>
  <%= f.submit "Submit edit", class: "btn btn-primary" %>
<% end %>

app/views/lists/index.html.erb
<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://c1.wallpaperflare.com/preview/570/413/91/interior-theatre-theater-empty-theater.jpg)">
  Save your favorite movies
</div>
<div class="lists-line-title">
  <h2>Your personnal lists</h2>
</div>
<div class="lists-container">
  <% @user_lists.each do |list| %>
  <div class="list">
    <div class="list-img">
      <%= cl_image_tag list.photo.key, crop: :fill %>
    </div>
    <div class="list-gradient">
    </div>
    <div class="list-title">
    <%= link_to list.name, list_path(list) %>
    </div>
  </div>
    <% end %>
  <div class="list" id="addlist-container">
    <div id="addlist">
      <%= link_to new_list_path do %>
        <i class="fas fa-plus"></i>
      <% end %>
    </div>
  </div>
</div>

app/views/lists/new.html.erb
<div class="new-list-container">
<h1>Add a new list</h1>

<%= simple_form_for [@list] do |f| %>
  <%= f.input :name, required: true %>
  <%= f.input :photo, as: :file, required: true %>
  <%= f.submit "Submit new list", class: "btn btn-primary" %>
<% end %>
</div>

app/views/lists/show.html.erb
 <div class="list-header">
  <div class="list-header-title">
    <div class="list-header-title-title">
      <h1><%= @list.name.upcase %></h1>
      <% unless @list.user == current_user %>
      <h3>by <%= @list.user.nickname %></h3>
      <% end %>
    </div>
    <div class="list-header-title-nickname">
    </div>
  </div>
  <% if @list.user_id == current_user.id %>
    <div class="list-header-buttons">
      <div class="btn btn-primary"><%= link_to new_list_bookmark_path(@list) do %>
        <i class="fas fa-plus"></i>
        <% end %>
      </div>
        <div id="edit-button" class="btn btn-success"><%= link_to "#" do %>
        <i class="far fa-edit"></i>
      <% end %>
      </div>
      <div class="btn btn-danger" id="remove-movie">
        <%= link_to list_path(@list),
                method: :delete,
                data: { confirm: "Are you sure?" } do %>
                <i class="fas fa-trash"></i>
                <% end %>
      </div>
    </div>
  <% end %>
</div>

<div class="movies-container">
  <% @list.bookmarks.each do |bookmark| %>
  <div class="movie-container">
    <div class="card-movie">
      <%= image_tag bookmark.movie.poster_url , alt: "Poster" %>
      <div class="card-movie-infos">
        <div>
          <h2><%=link_to bookmark.movie.title, movie_path(bookmark.movie.id) %></h2>
          <p><%=bookmark.movie.overview %></p>
          <h3 id="comment" ><i class="fas fa-comment-dots"> "</i><%=bookmark.comment %>"</h3>
        </div>
        <div class="movie-rating list-rating">
          <% (bookmark.movie.rating.to_i).times do %>
          <div class="star">
            <h2><i class="fas fa-star"></i></h2>
          </div>
          <% end %>
        </div>
      <div id="handle">
        <i class="fas fa-arrows-alt"></i>
      </div>
      </div>
      <button id="destroy-button" type="button" class="btn btn-danger hidden"><%= link_to "Remove from this list",
                    list_bookmark_path(bookmark.movie.id),
                    method: :delete,
                    data: { confirm: "Are you sure?" }
                    %></button>
    </div>
  </div>
  <% end %>
</div>

app/views/movies/edit.html.erb
<div class="new-list-container">
  <div class="new-list-container-title">
    <h1>Have you seen this movie?</h1>
  </div>
<%= simple_form_for [@movie] do |f| %>
  <%= f.input :seen, as: :boolean, label: "Seen" %>
  <%= f.input :seen_date, as: :date, label: "When?", id: "seen-checkbox" %>
  <div class="youtube-edit-button">
    <h3>
      <i class="fab fa-youtube"></i>
    </h3>
  </div>
  <div id="youtube-edit" class="youtube-hidden">
    <%= f.input :youtube_url, placeholder: "Youtube share link, like https://youtu.be/nPQ7om598OM", id:"youtube-edit" %>
  </div>
  <hr>
  <%= f.submit "Submit new movie", class: "btn btn-primary" %>
<% end %>
</div>

app/views/movies/index.html.erb
<div class="header">

  <% comment do %>
  <div class="search-container">
    <div class="search-input">
    <%= form_tag movies_path, method: :get do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Find a movie"
      %>
    </div>
    <% end %>
  </div>
    <div class="search-button">
      <%= submit_tag "Search", class: "btn btn-primary" %>
    </div>
  <% end %>

  <div class="index-header-button">
    <button id="add-button" type="button" class="btn btn-primary header-btn"><%= link_to new_movie_path do %>
      <i class="fas fa-plus"></i>
    <% end %>
    </button>
    <button type="button" class="btn btn-danger header-btn" id="edit-button"><%= link_to "#" do %>
      <i class="fas fa-trash"></i>
    <% end %>
    </button>
  </div>
</div>

<% comment do %>
<div class="movies-index-container">
  <% @movies.each do |movie| %>
    <%= render 'shared/movie_card', movie: movie %>
  <% end %>
</div>
<% comment end %>

  <div id="root"></div>

app/views/movies/new.html.erb
<div class="new-list-container">
<h1>Add a new movie</h1>
<%= simple_form_for [@movie] do |f| %>
  <%= f.input :title %>
  <%= f.input :youtube_url, placeholder: "Youtube share link, like https://youtu.be/nPQ7om598OM", pattern: "/^(https:\/\/youtu.be\/)(.*)$/"  %>
  <%= f.submit "Save this movie", class: "btn btn-primary" %>
<% end %>
  <hr>
</div>

<div class="result-container">
  <h3>Result Preview</h3>
  <div id="results">
  </div>
</div>

app/views/movies/seen.html.erb
<div class="seen-list-container">
  <div class="seen-list">
  <h1><%= "#{pluralize(@seen_movies.count, 'movie')} watched" %></h1>
  <hr>
    <div class="seen-lists-container">
      <div class="seen-list-title">
        <ul>
        <% @seen_movies.each do |movie| %>
            <li><%= link_to movie.title, movie_path(movie) %></li>
        <% end %>
        </ul>
      </div>
      <div class="seen-list-date">
        <ul>
        <% @seen_movies.each do |movie| %>
            <li>Seen on <%= movie.seen_date.strftime("%Y %m %d") %></li>
        <% end %>
        </ul>
      </div>
    </div>
  </div>
  <div class="unseen-list">
    <h1><%= "#{pluralize(@unseen_movies.count, 'movie')} not watched" %></h1>
    <hr>
    <ul>
    <% @unseen_movies.each do |movie| %>
        <li><%= link_to movie.title, movie_path(movie) %></li>
    <% end %>
    </ul>
  </div>
</div>

app/views/movies/show.html.erb
<div class="movie-show-header">
  <div class="header-title">
    <h1><%= @movie.title %></h1>
  </div>
  <% if @movie.user_id == current_user.id %>
    <% if @movie.seen %>
      <div class="movie-seen">
        <div class="movie-seen-icone">
        <%= link_to edit_movie_path do %>
          <i class="far fa-eye"></i>
        <% end %>
        </div>
        <div class="movie-seen-date">
          <h3><%= "Seen on #{@movie.seen_date.strftime("%Y %m %d")}" %></h3>
        </div>
      </div>
    <% else %>
      <div class="movie-not-seen">
        <%= link_to edit_movie_path do %>
          <i class="far fa-eye-slash"></i>
        <% end %>
      </div>
    <% end %>

      <div class="header-button">
        <div class="btn btn-danger" id="remove-movie">
        <%= link_to movie_path(@movie),
                method: :delete,
                data: { confirm: "Are you sure?" } do %>
                <i class="fas fa-trash"></i>
                <% end %>
        </div>
      </div>

  <% end %>
</div>

<div class="movie-show">
  <div class="movie-poster">
    <%= image_tag @movie.poster_url , alt: "Poster" %>
  </div>
  <div class="movie-infos">
    <div class="movie-show-overview">
      <h2><%= @movie.overview %></h2>
    </div>
  <h3><%= @movie.year %></h3>
  <h3><%= @movie.genre %></h3>
  <h3><%= @movie.director %></h3>
  <h3><%= @movie.actor %></h3>
  <div class="movie-rating">
  <% if @movie.rating %>
    <% rating = @movie.rating %>
    <% (rating.first(3).to_f.ceil).times do %>
      <div class="star">
        <h2><i class="fas fa-star"></i></h2>
      </div>
    <% end %>
  <% end %>
  </div>
    <div class="youtube-container">
      <div class="youtube-video">
        <% if @movie.youtube_url %>
          <iframe width="100%" height="280" src = <%=@movie.youtube_url%> title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://c1.wallpaperflare.com/preview/570/413/91/interior-theatre-theater-empty-theater.jpg)">
  <div class="card-category-title">
    <h1>MY WATCH LIST</h1>
    <h3>Save your favorite movies</h3>
  </div>
</div>
<div class="lists-line-title">
  <h2>Lists of the community</h2>
</div>
<div class="lists-container">
  <% @lists.each do |list| %>
  <div class="list">
    <div class="list-img">
      <%= cl_image_tag list.photo.key, crop: :fill %>
    </div>
    <div class="list-gradient">
    </div>
    <div class="list-title">
      <%= link_to list.name.upcase, list_path(list) %>
    </div>
    <div class="list-user-nickname">
      <h3>By <%= list.user.nickname %></h3>
    </div>
  </div>
    <% end %>
  </div>
</div>

app/views/shared/_movie_card.html.erb
<div class="movie-card-container">
  <div class="movie-body">
    <div class="movie-img">
      <%= image_tag movie.poster_url , alt: "Poster" %>
    </div>

    <div class="movie-info">
      <h5 class="card-title"><%= link_to movie.title, movie_path(movie) %></h5>
      <h6><%= movie.year %></h6>
      <h6><%= movie.genre %></h6>
      <h6><%= movie.overview %></h6>
      <% if movie.seen %>
        <div class="index-movie-seen">
          <i class="far fa-eye"></i>
        </div>
      <% else %>
        <div class="index-movie-not-seen">
          <i class="far fa-eye-slash"></i>
        </div>
      <% end %>
    </div>
  </div>

  <div class="movie-delete-button hidden" id="destroy-button">
  <%= link_to movie_path(movie),
          class: "btn btn-danger",
          method: :delete,
          data: { confirm: "Are you sure?" } do %>
    <i class="fas fa-trash"></i>
  <% end %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag src="https://image.flaticon.com/icons/png/512/195/195158.png" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <div class="header__item <%= "header__item--active" if controller_name == "lists" && action_name == "index" %>">
        <li class="nav-item">
          <%= link_to 'MyLists', lists_path %>
        </li>
      </div>
      <div class="header__item <%= "header__item--active" if controller_name == "movies" && action_name == "index" %>">
        <li class="nav-item">
          <%= link_to 'MyMovies', movies_path %>
        </li>
      </div>
      <div class="header__item <%= "header__item--active" if controller_name == "movies" && action_name == "seen" %>">
        <li class="nav-item">
          <%= link_to 'Watched', movies_seen_path %>
        </li>
      </div>
        <li class="nav-item dropdown">
          <%= image_tag "https://s1.qwant.com/thumbr/0x380/0/2/b3f2283456afd98cfcad9cf17d8b9c905b58f3077525ea90acdf6b1217f8d4/user-icon-symbol-sign-vector.jpg?u=https%3A%2F%2Fstatic.vecteezy.com%2Fsystem%2Fresources%2Fpreviews%2F000%2F649%2F115%2Foriginal%2Fuser-icon-symbol-sign-vector.jpg&q=0&b=1&p=0&a=0", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            <%= link_to "Edit profil", edit_user_registration_path, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>


<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
      <div class="header__item <%= "header__item--active" if controller_name == "lists" && action_name == "index" %>">
        <li class="nav-item">
          <%= link_to 'Lists', lists_path %>
        </li>
      </div>
      <div class="header__item <%= "header__item--active" if controller_name == "movies" && action_name == "index" %>">
        <li class="nav-item">
          <%= link_to 'Movies', movies_path %>
        </li>
      </div>
      <div class="header__item <%= "header__item--active" if controller_name == "movies" && action_name == "seen" %>">
        <li class="nav-item">
          <%= link_to 'Watched', movies_seen_path %>
        </li>
      </div>
      </ul>
    </div>